export default [
  {
    name: "Cat",
    breeds: [
      "Persian",
      "Tabby",
      "Domestic Medium-hair",
      "British Short Hair Mix",
      "Maine Coon Cat Mix",
      "Clouded Leopard",
      "Scottish Highland Fold",
      "British Longhair",
      "Foldex",
      "Abyssinian",
      "Aegean",
      "American Bobtail",
      "American Curl",
      "Aphrodite Giant",
      "Arabian Mau",
      "Asian",
      "Asian Semi-longhair",
      "Australian Mist",
      "Balinese",
      "Bambino",
      "Bengal",
      "Birman",
      "Bombay",
      "Brazilian Shorthair",
      "British Longhair",
      "British Shorthair",
      "Burmese",
      "Burmilla",
      "California Spangled",
      "Chantilly-Tiffany",
      "Chartreux",
    ],
  },
  {
    name: "Dog",
    breeds: [
      "Lhasa Apso",
      "Pomeranian Female Puppy",
      "Rottweiler Male Puppy",
      "Samoyed Puppy",
      "Cocker Spaniel Puppy",
      "Golden Retriever Puppy",
      "Lafa Breed",
      "Long Coat German Shepherd",
      "Dachshund Dog",
      "Pure husky",
      "Pure Pug",
      "Siberian Husky",
      "Japanese Spitz",
      "Rasian Samoyed Dog",
      "Coton De Tulear Dog",
      "American Eskimo Dog",
      "Doberman Puppy",
      "Border Coolie",
      "Toy Pomeranian Male",
      "PITBUL TERRIER",
      "Sizzu",
      "Laca Dog",
      "Doberman Shepherd",
    ],
  },
  {
    name: "Bird",
    breeds: [
      "Tame cockatiel",
      "Australian Dove",
      "Japanese Jepy",
      "Bombai fancy",
      "Fulvous whistling-duck",
      "Crimson Rosella",
      "Budgerigar",
      "African Gray Parrot",
      "Alexandrine Parakeet",
      "Cockatiel",
      "Eurasian Collared Dove",
      "Diamond Dove",
      "Java Sparrow",
      "Zebra Finch",
      "Star finch diamond",
      "Guinea Fowl",
      "Lutino cockatiel",
      "Koyel",
      "Perblue Fischer",
      "Parrot",
      "Buff Polish",
      "Albino Cockatiel",
      "Senegal parrot",
      "Java Finchs",
      "Gouldian Finchs",
      "African Grey",
      "Macaw",
      "Mulaccan & Greater sulphur crested cockatoo",
      "Sun Conure",
      "Green-cheeked Conure",
      "Blue-crowned Conure",
      "African Grey Parrot",
      "Yellow-naped Amazon",
      "Macaw",
      "Cockatoo",
    ],
  },
];
