const colorData: string[] = [
  "Black",
  "White",
  "Brown",
  "Gray",
  "Red",
  "Orange",
  "Yellow",
  "Green",
  "Blue",
  "Light Brown",
  "Dark Brown",
  "Light Gray",
  "Dark Gray",
  "Golden",
  "Silver",
  "Cream",
  "Tan",
  "Reddish Brown",
  "Pale Yellow",
  "Light Blue",
  "Dark Blue",
  "Pink",
  "Light Pink",
  "Purple",
  "Light Purple",
  "Sky Blue",
  "Olive Green",
  "Bright Green",
  "Bright Yellow",
  "Peach",
  "Light Green",
  "Pale Orange",
  "Bright Red",
  "Pale Pink",
  "Off-White",
  "Deep Blue",
  "Charcoal",
  "Sandy",
  "Chestnut",
  "Bluish Gray",
  "Greenish Yellow",
  "Reddish Orange",
  "Steel Gray",
  "Pale Blue",
  "Light Gold",
  "Ash Gray",
  "Bright Blue",
  "Pale Purple",
  "Dark Green",
  "Soft White",
];

export default colorData;
