export { default as AddCart } from './AddCart.svg';
export { default as Adoption } from './Adoption.svg';
export { default as ArrowLeft } from './ArrowLeft.svg';
export { default as ArrowRight } from './ArrowRight.svg';
export { default as Bird } from './Bird.svg';
export { default as Calendar } from './Calendar.svg';
export { default as Cart } from './Cart.svg';
export { default as Cat } from './Cat.svg';
export { default as Certificate } from './Certificate.svg';
export { default as Crown } from './Crown.svg';
export { default as Delete } from './Delete.svg';
export { default as Dog } from './Dog.svg';
export { default as Filter } from './Filter.svg';
export { default as Heart } from './Heart.svg';
export { default as HeartOutline } from './HeartOutline.svg';
export { default as Hospital } from './Hospital.svg';
export { default as Like } from './Like.svg';
export { default as LocationDot } from './LocationDot.svg';
export { default as LocationDotOutline } from './LocationDotOutline.svg';
export { default as Message } from './Message.svg';
export { default as Percentage } from './Percentage.svg';
export { default as Rabbit } from './Rabbit.svg';
export { default as Search } from './Search.svg';
export { default as Share } from './Share.svg';
export { default as Star } from './Star.svg';
export { default as Upload } from './Upload.svg';
export { default as User } from './User.svg';
export { default as Vet } from './Vet.svg';
export { default as Video } from './Video.svg';
export { default as Facebook } from './Facebook.svg';
export { default as Google } from './Google.svg';

// SVG component type
export type SvgIconProps = React.SVGProps<SVGSVGElement>;
