const VetsData = [
  {
    id: 0,
    name: "Dr. Maria Lamprou",
    designation: "Veterinarian, MRCVS",
    star: 5.0,
    license: true,
    profilePic: "/vets/vet1.webp",
    description:
      "Hello! I am Dr Maria Lamprou and I graduated with a distinction from the Veterinary School of Aristotle University of Thessaloniki in 2019. On the same year, I completed a postgraduate training in Anesthesia and Critical Care in the same department and currently I study towards a Certificate in Small Animal Medicine. I’m an experienced General Practitioner, with a passion on emergencies and soft tissue surgeries. I attend multiple courses throughout the year to keep my knowledge up to date. I used to run my family veterinary clinic in Greece for more than 2 years and since September 2022 I have been treating pets in the Uk. Feel free to book an appointment with me and go through your pet’s needs together. I look forward meeting you both!",
    species: ["Dog", "Cat"],
    areaOfInterest: [
      "Emergency",
      "Dermatology",
      "Nutrition",
      "Behavior",
      "Preventive",
      "Ophthalmology",
    ],
    licenses: ["England (ENG, GB)"],
    availableSlots: [
      "10:00 AM",
      "11:10 AM",
      "12:20 PM",
      "1:30 PM",
      "2:40 PM",
      "3:50 PM",
      "5:00 PM",
    ],
    fee: 3000,
    totalFee: 3500,
    reviews: [
      {
        id: 0,
        name: "Ben Walters",
        date: "August 2024",
        review:
          "Professional, and caring. Maria was incredibly knowledgeable and able to prescribe the correct medication, provide guidance on why that medication was chosen, and information on next steps. Highly recommend.",
        profilePic: "B",
      },
      {
        id: 1,
        name: "Bridget Dallow",
        date: "August 2024",
        review: "So very helpful excellent service would recommend to anyone",
        profilePic: "B",
      },
      {
        id: 2,
        name: "Eleanor Lock",
        date: "August 2024",
        review:
          "Really lovely and friendly, as well as responsive and approachable. Maria’s support was helpful!",
        profilePic: "E",
      },
      {
        id: 3,
        name: "Marta Foina",
        date: "August 2024",
        review:
          "very kind and helpful Doctor, will definitely call her again if we need to!",
        profilePic: "M",
      },
    ],
  },
  {
    id: 1,
    name: "Dr. Philomena Abang",
    designation: "Veterinarian, BSc BVSc MRCVS",
    star: 5.0,
    license: true,
    profilePic: "/vets/vet2.webp",
    description:
      "Hello! I originate from Nigeria and received both my degrees in Biological Sciences and Veterinary medicine from my studies in South Africa. I have lived and been a practising vet in various parts of the UK over the last 10 years specifically working in small animal private practice. I've fostered and rescued a few animals over the years and currently reside in Manchester with my black cat Salem, whom I rescued within my first year in the UK. I enjoy Japanese anime, dance and sports, occasionally playing social tag rugby for a Manchester league. Please be aware that due to strict regulations set by the UK veterinary governing body, I would not be able to provide prescriptions. I am instead happy to advise about alternative over-the-counter options that can be used safely. I particularly love consulting and assisting pet owners directly so do feel free to ask me any question about your furry friend's health and I will endeavour to give you clear and understanding advice to ease any worries.",
    species: ["Dog", "Cat"],
    areaOfInterest: [
      "Emergency",
      "Dermatology",
      "Nutrition",
      "Behavior",
      "Preventive",
      "Ophthalmology",
    ],
    licenses: ["England (ENG, GB)"],
    availableSlots: [
      "10:00 AM",
      "11:10 AM",
      "12:20 PM",
      "1:30 PM",
      "2:40 PM",
      "3:50 PM",
      "5:00 PM",
    ],
    fee: 4000,
    totalFee: 4500,
    reviews: [
      {
        id: 0,
        name: "Ben Walters",
        date: "August 2024",
        review:
          "Professional, and caring. Maria was incredibly knowledgeable and able to prescribe the correct medication, provide guidance on why that medication was chosen, and information on next steps. Highly recommend.",
        profilePic: "B",
      },
      {
        id: 1,
        name: "Bridget Dallow",
        date: "August 2024",
        review: "So very helpful excellent service would recommend to anyone",
        profilePic: "B",
      },
      {
        id: 2,
        name: "Eleanor Lock",
        date: "August 2024",
        review:
          "Really lovely and friendly, as well as responsive and approachable. Maria’s support was helpful!",
        profilePic: "E",
      },
      {
        id: 3,
        name: "Marta Foina",
        date: "August 2024",
        review:
          "very kind and helpful Doctor, will definitely call her again if we need to!",
        profilePic: "M",
      },
    ],
  },
  {
    id: 2,
    name: "Dr. Hyun Yang",
    designation: "Veterinarian, MRCVS",
    star: 4.5,
    license: true,
    profilePic: "/vets/vet3.webp",
    description:
      "Hi, I am a small animal (dogs and cats) vet currently working at a 24 hour first opinion hospital. My main areas of interest are oncology, internal medicine, and surgery.",
    species: ["Dog", "Cat"],
    areaOfInterest: [
      "Emergency",
      "Dermatology",
      "Nutrition",
      "Behavior",
      "Preventive",
      "Ophthalmology",
    ],
    licenses: ["England (ENG, GB)"],
    availableSlots: [
      "10:00 AM",
      "11:10 AM",
      "12:20 PM",
      "1:30 PM",
      "2:40 PM",
      "3:50 PM",
      "5:00 PM",
    ],
    fee: 4000,
    totalFee: 4500,
    reviews: [
      {
        id: 0,
        name: "Ben Walters",
        date: "August 2024",
        review:
          "Professional, and caring. Maria was incredibly knowledgeable and able to prescribe the correct medication, provide guidance on why that medication was chosen, and information on next steps. Highly recommend.",
        profilePic: "B",
      },
      {
        id: 1,
        name: "Bridget Dallow",
        date: "August 2024",
        review: "So very helpful excellent service would recommend to anyone",
        profilePic: "B",
      },
      {
        id: 2,
        name: "Eleanor Lock",
        date: "August 2024",
        review:
          "Really lovely and friendly, as well as responsive and approachable. Maria’s support was helpful!",
        profilePic: "E",
      },
      {
        id: 3,
        name: "Marta Foina",
        date: "August 2024",
        review:
          "very kind and helpful Doctor, will definitely call her again if we need to!",
        profilePic: "M",
      },
    ],
  },
  {
    id: 3,
    name: "Dr. Amy Woodhouse",
    designation: "Veterinarian, BVetMed MRCVS",
    star: 5.0,
    license: true,
    profilePic: "/vets/vet4.webp",
    description:
      "Hello, my name is Amy. I have been qualified as a vet for 22 years and have worked in a large variety of busy small animal clinics treating mainly dogs and cats but also small furries. I enjoy all aspects of Veterinary medicine, in particular internal medicine, ophthalmology and consulting . I am also a fully qualified Veterinary Acupuncturist and in addition to my small animal clinic work I also work in a busy canine rehabilitation centre with dogs that are recovering from orthopaedic, muscular or neurological problems. Meeting and helping people and their pets is my passion Outside of work I love to walk my two rescue dogs in the beautiful surrounding countryside near to me and spend time with my family. Please note that the Royal College of Veterinary Surgeons has now revoked the ability of vets to prescribe remotely, which we were given special dispensation for during Covid, so we are unable to prescribe prescription-only medication. I can however, offer advice about possible over-the-counter drugs which may be suitable for your pet. In many cases I am able to offer advice and second opinions without the need for medication or advise on which medications, treatments or diagnostics I would recommend so you could discuss further in person when you are able to visit a Veterinary clinic.",
    species: ["Dog", "Cat"],
    areaOfInterest: [
      "Emergency",
      "Dermatology",
      "Nutrition",
      "Behavior",
      "Preventive",
      "Ophthalmology",
    ],
    licenses: ["England (ENG, GB)"],
    availableSlots: [
      "10:00 AM",
      "11:10 AM",
      "12:20 PM",
      "1:30 PM",
      "2:40 PM",
      "3:50 PM",
      "5:00 PM",
    ],
    fee: 5000,
    totalFee: 5500,
    reviews: [
      {
        id: 0,
        name: "Ben Walters",
        date: "August 2024",
        review:
          "Professional, and caring. Maria was incredibly knowledgeable and able to prescribe the correct medication, provide guidance on why that medication was chosen, and information on next steps. Highly recommend.",
        profilePic: "B",
      },
      {
        id: 1,
        name: "Bridget Dallow",
        date: "August 2024",
        review: "So very helpful excellent service would recommend to anyone",
        profilePic: "B",
      },
      {
        id: 2,
        name: "Eleanor Lock",
        date: "August 2024",
        review:
          "Really lovely and friendly, as well as responsive and approachable. Maria’s support was helpful!",
        profilePic: "E",
      },
      {
        id: 3,
        name: "Marta Foina",
        date: "August 2024",
        review:
          "very kind and helpful Doctor, will definitely call her again if we need to!",
        profilePic: "M",
      },
    ],
  },
  {
    id: 4,
    name: "Dr. Dorothy Bodle",
    designation: "Veterinarian, BVSc, BSc (Hons) MRCVS",
    star: 5.0,
    license: true,
    profilePic: "/vets/vet5.webp",
    description:
      "Qualifying as a vet post my second degree is one of the best work life choices I have ever made. I get to spend time with animals all day helping to both maintain and improve their health status. It is such a rewarding job to see this happening and know I have been able to do so.",
    species: ["Dog", "Cat", "Small Mammal"],
    areaOfInterest: [
      "Emergency",
      "Dermatology",
      "Nutrition",
      "Behavior",
      "Preventive",
      "Ophthalmology",
    ],
    licenses: ["Wales (WLS, GB)", "England (ENG, GB)"],
    availableSlots: [
      "10:00 AM",
      "11:10 AM",
      "12:20 PM",
      "1:30 PM",
      "2:40 PM",
      "3:50 PM",
      "5:00 PM",
    ],
    fee: 5000,
    totalFee: 5500,
    reviews: [
      {
        id: 0,
        name: "Ben Walters",
        date: "August 2024",
        review:
          "Professional, and caring. Maria was incredibly knowledgeable and able to prescribe the correct medication, provide guidance on why that medication was chosen, and information on next steps. Highly recommend.",
        profilePic: "B",
      },
      {
        id: 1,
        name: "Bridget Dallow",
        date: "August 2024",
        review: "So very helpful excellent service would recommend to anyone",
        profilePic: "B",
      },
      {
        id: 2,
        name: "Eleanor Lock",
        date: "August 2024",
        review:
          "Really lovely and friendly, as well as responsive and approachable. Maria’s support was helpful!",
        profilePic: "E",
      },
      {
        id: 3,
        name: "Marta Foina",
        date: "August 2024",
        review:
          "very kind and helpful Doctor, will definitely call her again if we need to!",
        profilePic: "M",
      },
    ],
  },
  {
    id: 5,
    name: "Dr. Dorothy Bodle",
    designation: "Veterinarian, MA VetMB MRCVS",
    star: 5.0,
    license: true,
    profilePic: "/vets/vet6.webp",
    description:
      "Dr. Lucy Jarvis is a licensed Veterinary Surgeon in England. Dr. Jarvis has experience with Companion animals (such as dogs and cats). Dr. Jarvis has been practicing on Vetster since June 2024.",
    species: ["Dog", "Cat"],
    areaOfInterest: [
      "Emergency",
      "Dermatology",
      "Nutrition",
      "Behavior",
      "Preventive",
      "Ophthalmology",
    ],
    licenses: ["England (ENG, GB)"],
    availableSlots: [
      "10:00 AM",
      "11:10 AM",
      "12:20 PM",
      "1:30 PM",
      "2:40 PM",
      "3:50 PM",
      "5:00 PM",
    ],
    fee: 5000,
    totalFee: 5500,
    reviews: [
      {
        id: 0,
        name: "Ben Walters",
        date: "August 2024",
        review:
          "Professional, and caring. Maria was incredibly knowledgeable and able to prescribe the correct medication, provide guidance on why that medication was chosen, and information on next steps. Highly recommend.",
        profilePic: "B",
      },
      {
        id: 1,
        name: "Bridget Dallow",
        date: "August 2024",
        review: "So very helpful excellent service would recommend to anyone",
        profilePic: "B",
      },
      {
        id: 2,
        name: "Eleanor Lock",
        date: "August 2024",
        review:
          "Really lovely and friendly, as well as responsive and approachable. Maria’s support was helpful!",
        profilePic: "E",
      },
      {
        id: 3,
        name: "Marta Foina",
        date: "August 2024",
        review:
          "very kind and helpful Doctor, will definitely call her again if we need to!",
        profilePic: "M",
      },
    ],
  },
];

export default VetsData;
