import "@/src/styles/globals.css";

import { Toaster as HotToaster } from "react-hot-toast";
import { Toaster } from "@/src/components/ui/toaster";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

import Navbar from "@/src/components/navbar";
import Footer from "@/src/components/footer";

import ProgressBarProvider from "@/src/components/providers/ProgressBarProvider";
import { AuthProvider } from "@/src/components/providers/AuthProvider";

export const metadata = {
  title: "Biluibaba",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="selection:bg-stone-950 selection:text-white">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar/>
          
          <HotToaster
            position="bottom-right"
            toastOptions={{
              success: {
                style: {
                  color: "green",
                },
              },
              error: {
                style: {
                  color: "red",
                },
              },
            }}
          />
          <Toaster />
          <div className="pt-32">
          <ProgressBarProvider>{children}</ProgressBarProvider>
          </div>
          <Footer/>
        </AuthProvider>
      </body>
    </html>
  );
}
