import "@/src/styles/globals.css";

import { Toaster } from "react-hot-toast";

import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

import Navbar from "@/src/components/navbar";
import Footer from "@/src/components/footer";

import ProgressBarProvider from "@/src/components/providers/ProgressBarProvider";
import { AuthProvider } from "@/src/components/providers/AuthProvider";

export const metadata = {
  title: "Biluibaba",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="selection:bg-stone-950 selection:text-white">
      <body className={roboto.className}>
        <AuthProvider>
          <Navbar></Navbar>
          <Toaster
            position="bottom-right"
            toastOptions={{
              success: {
                style: {
                  color: "green",
                },
              },
              error: {
                style: {
                  color: "red",
                },
              },
            }}
          />
          <ProgressBarProvider>{children}</ProgressBarProvider>
          <Footer></Footer>
        </AuthProvider>
      </body>
    </html>
  );
}
