name: Staging Deploy

on:
  push:
    branches:
      - initial-ecommerce-release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Admin Dependencies
      run: npm install
      working-directory: ./admin

    - name: Build Admin
      run: npm run build
      working-directory: ./admin

    - name: Build Client
      run: |
        npm install
        npm run build
      working-directory: ./client

    - name: Build Vendor App
      run: |
        npm install
        npm run build
      working-directory: ./app

    - name: Install Backend Dependencies
      run: npm install
      working-directory: ./server